[build]
  publish = "."

[[headers]]
  for = "/*.wasm"
  [headers.values]
    "Content-Type" = "application/wasm"
    "Cache-Control" = "public, max-age=31536000"

[[headers]]
  for = "/*.data"
  [headers.values]
    "Content-Type" = "application/octet-stream"
    "Cache-Control" = "public, max-age=31536000"

[[headers]]
  for = "/*.unityweb"
  [headers.values]
    "Content-Type" = "application/octet-stream"
    "Cache-Control" = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000"

# Redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200